services:
  ripx:
    image: ghcr.io/project-absolute/ripx:dev
    hostname: ripx
    container_name: ripx
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    restart: unless-stopped
